environment:
  matrix:
  - COMPILER: MSVC_15
    ARCHITECTURE: x64
    BUILD_TESTS: true
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - COMPILER: MSVC_15
    ARCHITECTURE: x86
    BUILD_TESTS: true
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - COMPILER: MINGW_73
    ARCHITECTURE: x64
    BUILD_TESTS: true
  - COMPILER: MINGW_532
    ARCHITECTURE: x86
    BUILD_TESTS: true

build:
  verbosity: detailed
  parallel: true

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  #######################################################################################
  # Install Ninja
  #######################################################################################
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version
  
  #######################################################################################
  # Install doxygen
  #######################################################################################
  - ps: >-
      If ($env:BUILD_DOCU -Match "true") {
        $env:DOXYGEN_URL="http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.10.windows.bin.zip"
        appveyor DownloadFile $env:DOXYGEN_URL -FileName doxygen.zip
        7z x doxygen.zip -oC:/projects/deps/doxygen-1.8.10 > $null
        $env:PATH="C:/projects/deps/doxygen-1.8.10;$env:PATH"
        doxygen --version
      }
  
  #######################################################################################
  # Update CMake
  #######################################################################################
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmd: ci\appveyor\setup_cmake.bat

before_build:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: set PATH=C:\Python37-x64;%PATH%
  - cmd: python -m pip install antlr4-python3-runtime six pyyaml click typing watchdog path.py jinja2==2.10.3
  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "MSVC_15" set PATH=C:\Qt\5.12\msvc2017_64\bin;%PATH%
  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "MSVC_15" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\vsdevcmd.bat" -arch=x64 -host_arch=x64
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "MSVC_15" set PATH=C:\Qt\5.12\msvc2017\bin;%PATH%
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "MSVC_15" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\vsdevcmd.bat" -arch=x86 -host_arch=x64
  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "MINGW_73" set PATH=C:\Qt\Tools\mingw730_64\bin;C:\Qt\5.12\mingw73_64\bin;%PATH%
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "MINGW_532" set PATH=C:\Qt\Tools\mingw530_32\bin;C:\Qt\5.11.3\mingw53_32\bin;%PATH%

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DFACELIFT_BUILD_TESTS=%BUILD_TESTS% -DFACELIFT_DISABLE_GTEST=ON
  - ninja
 # - if "%BUILD_TESTS%" == "true" (ctest) # when you want to run the tests, use this uncomment this line
